const cats=[['Todos','✨'],['Roupas','👕'],['Pokémon TCG','🃏'],['Hot Wheels','🚗'],['Perfumes','🌹'],['Ofertas','🔥']];
let selectedCategory='Todos',searchTerm='',cart=JSON.parse(localStorage.getItem('lagartin_cart')||'[]'),products=[],detailImageIndex=0,db=null;
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
try{if(window.FIREBASE_CONFIG?.projectId&&!String(window.FIREBASE_CONFIG.projectId).startsWith('COLE_')){firebase.initializeApp(window.FIREBASE_CONFIG);db=firebase.firestore()}}catch(e){console.error(e)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function renderCats(){catsEl().innerHTML=cats.map(([c,i])=>`<button class="cat ${selectedCategory===c?'active':''}" onclick="selectCategory('${c}')"><span class="ico">${i}</span>${c}</button>`).join('')}
function catsEl(){return document.getElementById('cats')}
function filtered(){return products.filter(p=>(selectedCategory==='Todos'||p.cat===selectedCategory)&&(String(p.name||'').toLowerCase().includes(searchTerm)||String(p.cat||'').toLowerCase().includes(searchTerm)))}
function renderProducts(){const list=filtered();document.getElementById('productTitle').textContent=selectedCategory==='Todos'?(searchTerm?'Resultados':'Destaques'):selectedCategory;document.getElementById('products').innerHTML=list.length?list.map(p=>`<article class="product" onclick="openDetail('${p.id}')"><div class="photo">${p.images?.[0]?`<img src="${p.images[0]}" style="width:100%;height:100%;object-fit:cover">`:p.emoji||'📦'}${p.images?.length>1?`<span class="photo-count">${p.images.length} fotos</span>`:''}<span class="condition">${esc(p.condition||'')}</span></div><div class="info"><div class="category-label">${esc(p.cat)}</div><div class="name">${esc(p.name)}</div><div class="price">${money(p.price)}</div><button class="buy" onclick="event.stopPropagation();addCart('${p.id}')">Adicionar</button></div></article>`).join(''):`<div class="empty">😕<br><br>Nenhum produto encontrado.<br><small>Tente outra busca ou categoria.</small></div>`}
function selectCategory(c){selectedCategory=c;renderCats();renderProducts();window.scrollTo({top:0,behavior:'smooth'})}
function clearFilters(){selectedCategory='Todos';searchTerm='';document.getElementById('search').value='';renderCats();renderProducts()}
document.getElementById('search').addEventListener('input',e=>{searchTerm=e.target.value.trim().toLowerCase();renderProducts()});
function focusSearch(){document.getElementById('search').focus();window.scrollTo({top:0,behavior:'smooth'})}function goHome(){clearFilters();window.scrollTo({top:0,behavior:'smooth'})}
function renderDetailGallery(p){const imgs=(Array.isArray(p.images)?p.images:[]).filter(Boolean);if(!imgs.length)return `<div class="detail-gallery"><div class="detail-photo">${p.emoji||'📦'}</div></div>`;const i=Math.max(0,Math.min(Number(detailImageIndex)||0,imgs.length-1));const arrows=imgs.length>1?`<button class="gallery-arrow prev" onclick="event.stopPropagation();changeDetailImage('${p.id}',-1)">‹</button><button class="gallery-arrow next" onclick="event.stopPropagation();changeDetailImage('${p.id}',1)">›</button><span class="gallery-count">${i+1}/${imgs.length}</span>`:'';const thumbs=imgs.length>1?`<div class="thumbs">${imgs.map((src,n)=>`<button class="thumb ${n===i?'active':''}" onclick="event.stopPropagation();setDetailImage('${p.id}',${n})"><img src="${src}" alt="Foto ${n+1}"></button>`).join('')}</div>`:'';return `<div class="detail-gallery"><div class="detail-photo swipeable" ontouchstart="galleryTouchStart(event)" ontouchend="galleryTouchEnd(event,'${p.id}')"><img src="${imgs[i]}" alt="${esc(p.name)}">${arrows}</div>${thumbs}</div>`}
let galleryTouchX=0;function galleryTouchStart(e){galleryTouchX=e.changedTouches?.[0]?.clientX||0}function galleryTouchEnd(e,id){const x=e.changedTouches?.[0]?.clientX||0;if(Math.abs(x-galleryTouchX)>45)changeDetailImage(id,x<galleryTouchX?1:-1)}
function setDetailImage(id,index){const p=products.find(x=>x.id===id);if(!p)return;detailImageIndex=Math.max(0,Math.min(index,(p.images?.length||1)-1));document.getElementById('detailContent').innerHTML=detailMarkup(p)}
function changeDetailImage(id,delta){const p=products.find(x=>x.id===id);if(!p||!p.images?.length)return;detailImageIndex=(detailImageIndex+delta+p.images.length)%p.images.length;document.getElementById('detailContent').innerHTML=detailMarkup(p)}
function detailMarkup(p){return `<div class="detail">${renderDetailGallery(p)}<div class="category-label">${esc(p.cat)}</div><h2>${esc(p.name)}</h2><div class="meta">Condição: ${esc(p.condition||'')}</div><p class="desc">${esc(p.desc||'')}</p><div class="detail-price">${money(p.price)}</div><button class="ig-btn" onclick="buyInstagram('${p.id}')">💬 Comprar pelo Instagram</button><button class="full-btn" onclick="addCart('${p.id}');closeDetail()">Adicionar ao carrinho</button></div>`}
function openDetail(id){const p=products.find(x=>x.id===id);if(!p)return;detailImageIndex=0;document.getElementById('detailContent').innerHTML=detailMarkup(p);document.getElementById('detailOverlay').classList.add('open')}function closeDetail(){document.getElementById('detailOverlay').classList.remove('open')}
function saveCart(){localStorage.setItem('lagartin_cart',JSON.stringify(cart));updateCount()}function addCart(id){if(products.some(p=>p.id===id)){cart.push(id);saveCart();toast('Produto adicionado ao carrinho 🛒')}}function updateCount(){const e=document.getElementById('cartCount');e.textContent=cart.length;e.style.display=cart.length?'grid':'none'}
function cartGroups(){const m=new Map();for(const id of cart){const p=products.find(x=>x.id===id);if(!p)continue;if(!m.has(id))m.set(id,{p,qty:0});m.get(id).qty++}return [...m.values()]}
function changeQty(id,d){if(d>0)cart.push(id);else{const i=cart.indexOf(id);if(i>=0)cart.splice(i,1)}saveCart();renderCart()}function removeAll(id){cart=cart.filter(x=>x!==id);saveCart();renderCart()}
function renderCart(){const el=document.getElementById('cartContent'),g=cartGroups();if(!g.length){el.innerHTML='<div class="cart-empty"><div style="font-size:52px">🛒</div><h3 style="margin:14px 0 6px;color:var(--text)">Seu carrinho está vazio</h3><div>Adicione um produto para vê-lo aqui.</div><button class="full-btn" onclick="closeCart();window.scrollTo({top:0,behavior:\'smooth\'})">Continuar comprando</button></div>';return}const total=g.reduce((s,x)=>s+x.p.price*x.qty,0),n=g.reduce((s,x)=>s+x.qty,0);el.innerHTML=`<div class="cart-list">${g.map(x=>`<div class="cart-item"><div class="cart-thumb">${x.p.images?.[0]?`<img src="${x.p.images[0]}" alt="${esc(x.p.name)}">`:x.p.emoji||'📦'}</div><div><div class="cart-name">${esc(x.p.name)}</div><div class="cart-unit">${money(x.p.price)} cada</div><div class="qty"><button onclick="changeQty('${x.p.id}',-1)">−</button><strong>${x.qty}</strong><button onclick="changeQty('${x.p.id}',1)">+</button></div></div><button class="cart-remove" onclick="removeAll('${x.p.id}')">✕</button></div>`).join('')}</div><div class="cart-summary"><div><span>${n} ${n===1?'item':'itens'}</span><br><strong>Total</strong></div><strong>${money(total)}</strong></div><button class="ig-btn" onclick="checkoutInstagram()">💬 Enviar pedido pelo Instagram</button><p style="font-size:11px;color:var(--muted);line-height:1.5">Vamos copiar uma mensagem com seu pedido e abrir o Direct do @lag4rt1n_.</p>`}
function openCart(){renderCart();document.getElementById('cartOverlay').classList.add('open')}function closeCart(){document.getElementById('cartOverlay').classList.remove('open')}function closeOnBackdrop(e,id){if(e.target.id===id)document.getElementById(id).classList.remove('open')}
const INSTAGRAM_USERNAME='lag4rt1n_';function buildInstagramMessage(items){const total=items.reduce((s,p)=>s+p.price,0);return `Olá! Vim pelo LagartinShop e tenho interesse em comprar:\n\n${items.map(p=>`• ${p.name} — ${money(p.price)}`).join('\n')}\n\nTotal: ${money(total)}\n\nPode me passar as informações para finalizar a compra?`}
async function openInstagramWithMessage(message){try{await navigator.clipboard.writeText(message);toast('Mensagem copiada! Abrindo o Instagram…')}catch(e){toast('Mensagem pronta. Abra o Instagram.')}setTimeout(()=>location.href=`https://ig.me/m/${INSTAGRAM_USERNAME}`,450)}function buyInstagram(id){const p=products.find(x=>x.id===id);if(p)openInstagramWithMessage(buildInstagramMessage([p]))}function checkoutInstagram(){const items=cart.map(id=>products.find(p=>p.id===id)).filter(Boolean);if(items.length)openInstagramWithMessage(buildInstagramMessage(items))}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function loadProducts(){if(!db){document.getElementById('products').innerHTML='<div class="empty">⚙️<br><br>Configure o Firebase para carregar os produtos.</div>';return}db.collection('products').orderBy('createdAt','desc').onSnapshot(s=>{products=s.docs.map(d=>{const x=d.data();return {id:d.id,...x,cat:x.category||x.cat,desc:x.description||x.desc}});cart=cart.filter(id=>products.some(p=>p.id===id));saveCart();renderProducts() },e=>{console.error(e);document.getElementById('products').innerHTML='<div class="empty">Não foi possível carregar os produtos.</div>'})}
renderCats();renderProducts();updateCount();loadProducts();
